#!/usr/bin/env python

import sys
import zmq
from zmq.eventloop.ioloop import IOLoop

from mdp.broker import MDPBroker

if __name__ == '__main__':
    addr = sys.argv[1]
    print "MDPBroker listening on {0}".format(addr)
    broker = MDPBroker(zmq.Context(), addr)
    IOLoop.instance().start()
