#!/usr/bin/env python

import sys
import zmq
from zmq.eventloop.ioloop import IOLoop

from mdp.client import mdp_request


if __name__ == '__main__':
    addr, service, cmd = sys.argv[1], sys.argv[2], sys.argv[3]
    ctx = zmq.Context()
    socket = ctx.socket(zmq.REQ)
    socket.connect(addr)
    print mdp_request(socket, service, [cmd])
