#!/usr/bin/env python

import sys
import zmq
from zmq.eventloop.ioloop import IOLoop

from mdp.worker import MDPWorker


class MirrorWorker(MDPWorker):

    def on_request(self, msg):
        self.reply("Mirror|{0}|{1}|".format(id(self), msg))

if __name__ == '__main__':
    addr = sys.argv[1]
    ctx = zmq.Context()
    workers = [MirrorWorker(ctx, addr, "mirror") for x in range(10)]
    IOLoop.instance().start()
